import { ShippingDestination } from "./destination-type";

export const shippingDestinations: ShippingDestination[] = [
  {
    id: "1",
    from: "Jakarta",
    to: "Makassar",
    pricePerKg: 4000,
    minWeight: 50,
    deliveryEstimate: "5-6 hari",
  },
  {
    id: "2",
    from: "Jakarta",
    to: "Parepare",
    pricePerKg: 6000,
    minWeight: 100,
    deliveryEstimate: "6-7 hari",
  },
  {
    id: "3",
    from: "Jakarta",
    to: "Polman",
    pricePerKg: 7000,
    minWeight: 100,
    deliveryEstimate: "7-8 hari",
  },
  {
    id: "4",
    from: "Makassar",
    to: "Jakarta",
    pricePerKg: 4000,
    minWeight: 100,
    deliveryEstimate: "5-6 hari",
  },
  {
    id: "6",
    from: "Medan",
    to: "Jakarta",
    pricePerKg: 3500,
    minWeight: 100,
    deliveryEstimate: "3-4 hari",
  },
  {
    id: "7",
    from: "Jakarta",
    to: "Medan",
    pricePerKg: 3500,
    minWeight: 100,
    deliveryEstimate: "3-4 hari",
  },
  {
    id: "8",
    from: "Jakarta",
    to: "Palembang",
    pricePerKg: 2800,
    minWeight: 100,
    deliveryEstimate: "3-4 hari",
  },
  {
    id: "9",
    from: "Palembang",
    to: "Jakarta",
    pricePerKg: 2800,
    minWeight: 100,
    deliveryEstimate: "3-4 hari",
  },
  {
    id: "10",
    from: "Jakarta",
    to: "Surabaya",
    pricePerKg: 2000,
    minWeight: 100,
    deliveryEstimate: "1-2 hari",
  },
  {
    id: "11",
    from: "Jakarta",
    to: "Semarang",
    pricePerKg: 1700,
    minWeight: 100,
    deliveryEstimate: "1-2 hari",
  },
  {
    id: "12",
    from: "Semarang",
    to: "Jakarta",
    pricePerKg: 1700,
    minWeight: 100,
    deliveryEstimate: "1-2 hari",
  },
  {
    id: "12",
    from: "Jakarta",
    to: "Solo",
    pricePerKg: 2000,
    minWeight: 100,
    deliveryEstimate: "1-2 hari",
  },
  {
    id: "13",
    from: "Solo",
    to: "Jakarta",
    pricePerKg: 2000,
    minWeight: 100,
    deliveryEstimate: "1-2 hari",
  },
  {
    id: "14",
    from: "Jakarta",
    to: "Palu",
    pricePerKg: 9000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },

  {
    id: "15",
    from: "Palu",
    to: "Jakarta",
    pricePerKg: 9000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },

  {
    id: "16",
    from: "Jakarta",
    to: "Manado",
    pricePerKg: 11000,
    minWeight: 100,
    deliveryEstimate: "9-10 hari",
  },

  {
    id: "17",
    from: "Manado",
    to: "Jakarta",
    pricePerKg: 11000,
    minWeight: 100,
    deliveryEstimate: "9-10 hari",
  },

  {
    id: "18",
    from: "Jakarta",
    to: "Kendari",
    pricePerKg: 9500,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "19",
    from: "Kendari",
    to: "Jakarta",
    pricePerKg: 9500,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "20",
    from: "Jakarta",
    to: "Palopo",
    pricePerKg: 7000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "21",
    from: "Palopo",
    to: "Jakarta",
    pricePerKg: 7000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "22",
    from: "Jakarta",
    to: "Gorontalo",
    pricePerKg: 9000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "23",
    from: "Gorontalo",
    to: "Jakarta",
    pricePerKg: 9000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  // Add the rest of the destinations
];
