import { ShippingDestination } from "./destination-type";

export const shippingDestinations: ShippingDestination[] = [
  {
    id: "1",
    name: "JAKARTA - MAKASSAR",
    pricePerKg: 4000,
    minWeight: 50,
    deliveryEstimate: "5-6 hari",
  },
  {
    id: "2",
    name: "JAKARTA - PAREPARE",
    pricePerKg: 6000,
    minWeight: 100,
    deliveryEstimate: "6-7 hari",
  },
  {
    id: "3",
    name: "JAKARTA - POLMAN",
    pricePerKg: 7000,
    minWeight: 100,
    deliveryEstimate: "7-8 hari",
  },
  {
    id: "4",
    name: "JAKARTA - MAMUJU",
    pricePerKg: 7500,
    minWeight: 100,
    deliveryEstimate: "7-8 hari",
  },
  {
    id: "5",
    name: "JAKARTA - PALU",
    pricePerKg: 8500,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "6",
    name: "JAKARTA - MANADO",
    pricePerKg: 10000,
    minWeight: 100,
    deliveryEstimate: "9-10 hari",
  },
  {
    id: "7",
    name: "JAKARTA - KOLAKA",
    pricePerKg: 9000,
    minWeight: 100,
    deliveryEstimate: "10-12 hari",
  },
  {
    id: "8",
    name: "JAKARTA - BAUBAU",
    pricePerKg: 11000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "9",
    name: "JAKARTA - GORONTALO",
    pricePerKg: 9000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "10",
    name: "JAKARTA - BONE",
    pricePerKg: 7000,
    minWeight: 100,
    deliveryEstimate: "10-12 hari",
  },
  {
    id: "11",
    name: "JAKARTA - BULUKUMBA",
    pricePerKg: 7500,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "12",
    name: "JAKARTA - MANGKUTANA",
    pricePerKg: 8500,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "13",
    name: "JAKARTA - BITUNG",
    pricePerKg: 11000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "14",
    name: "JAKARTA - KOTA MOBAGU",
    pricePerKg: 11000,
    minWeight: 100,
    deliveryEstimate: "14-15 hari",
  },
  {
    id: "15",
    name: "JAKARTA - TERNATE",
    pricePerKg: 12000,
    minWeight: 100,
    deliveryEstimate: "14-15 hari",
  },
  {
    id: "16",
    name: "JAKARTA - AMBON",
    pricePerKg: 13000,
    minWeight: 100,
    deliveryEstimate: "12-13 hari",
  },
  {
    id: "17",
    name: "JAKARTA - TUAL",
    pricePerKg: 14000,
    minWeight: 100,
    deliveryEstimate: "14-15 hari",
  },
  {
    id: "18",
    name: "JAKARTA - BIAK",
    pricePerKg: 14000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "19",
    name: "JAKARTA - JAYAPURA",
    pricePerKg: 15000,
    minWeight: 100,
    deliveryEstimate: "15-16 hari",
  },
  {
    id: "20",
    name: "JAKARTA - SORONG",
    pricePerKg: 15000,
    minWeight: 100,
    deliveryEstimate: "14-15 hari",
  },
  {
    id: "21",
    name: "JAKARTA - TIMIKA",
    pricePerKg: 15000,
    minWeight: 100,
    deliveryEstimate: "14-15 hari",
  },
  {
    id: "22",
    name: "JAKARTA - MARAUKE",
    pricePerKg: 17000,
    minWeight: 100,
    deliveryEstimate: "15-16 hari",
  },
  {
    id: "23",
    name: "JAKARTA - KENDARI",
    pricePerKg: 10000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "24",
    name: "JAKARTA - WASIOR",
    pricePerKg: 16000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "25",
    name: "JAKARTA - MASAMBA",
    pricePerKg: 7500,
    minWeight: 100,
    deliveryEstimate: "7-8 hari",
  },
  {
    id: "26",
    name: "JAKARTA - MANOKWARI",
    pricePerKg: 13500,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "27",
    name: "JAKARTA - MOROTAI",
    pricePerKg: 25000,
    minWeight: 100,
    deliveryEstimate: "10-12 hari",
  },
  {
    id: "28",
    name: "JAKARTA - PALOPO",
    pricePerKg: 7500,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "29",
    name: "JAKARTA - SINJAI",
    pricePerKg: 7500,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "30",
    name: "JAKARTA - PINRANG",
    pricePerKg: 7500,
    minWeight: 100,
    deliveryEstimate: "7-8 hari",
  },
  {
    id: "31",
    name: "JAKARTA - JENEPONTO",
    pricePerKg: 6500,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "32",
    name: "JAKARTA - MOROWALI",
    pricePerKg: 10000,
    minWeight: 100,
    deliveryEstimate: "8-9 hari",
  },
  {
    id: "33",
    name: "JAKARTA - SOPPENG",
    pricePerKg: 7500,
    minWeight: 100,
    deliveryEstimate: "6-7 hari",
  },
  {
    id: "34",
    name: "JAKARTA - SENGKANG/WAJO",
    pricePerKg: 7500,
    minWeight: 100,
    deliveryEstimate: "6-7 hari",
  },
  {
    id: "35",
    name: "JAKARTA - AMURANG",
    pricePerKg: 9000,
    minWeight: 100,
    deliveryEstimate: "10-11 hari",
  },

  // Add the rest of the destinations
];
